<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Trace History</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome CSS for icons -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="../CSS/navbar.css">
  <link rel="stylesheet" href="../CSS/india_active_cases.css">
  
</head>
<body>
  <?php include 'image_holder.php'; ?>
  <?php include 'navbar.html'; ?>
  <div class="container">
   <div class="container mt-5">
      <div class="row">
        <div class="col-md-8 mx-auto text-center jumbotron bg-info text-white">
          <h2>Trace History</h2>
          <p>From the very detailed information in the bulletins, we created graphical representation of Karnataka Trace History via a tree diagram.
          </p>
          <!-- Add your charts or data visualization here -->
        </div>
      </div>
    </div>
    
    
    <div class="container mt-5">
      <div class="row">
        <!-- Column for sections -->
        
      <div class="col-md-12 icu-timeline">
        <h3>Basic Reproduction Number Based on Trace History</h3>
        <p>In epidemiology, the "basic reproduction number" of an infection can be thought of as the expected number of cases directly generated by one case. From the Karnataka Trace History we can plot the distribution of number of cases directly generated by each case, i.e. distribution of number of children across the infected patients.
        <br>These graphs were frozen on 26th June as the Media Bulletins after that did not contain contact information.
        <br>
In the above plot, only immediate successors [children] in the tree have been counted for each node, and not grandchildren or great grandchildren. A vast majority of cases have no children, which is due to the isolation and hospitalization measures.
<br>
However, the distribution seems to have a few people who have a very high number of children. This behaviour is sometime seen in an epidemic spread.
        </p>
      </div>
      </div>
  </div>

   
    <div class="container mt-5">
    <div class="row">
        <!-- Column for sections -->
        
        <div class="col-md-6">
            <div id="graphCanvas">
                <!-- Graph will be displayed here -->
                <?php generateImageHolder("ka_infocus","ka-child.svg","ka-child.html","ka_infectedchilderen_hist.R",2,[25],400,450)?>
            </div>
            </div>
    
         <!-- Column for graph -->
            <div class="col-md-6">
            <div id="graphCanvas">
                <!-- Graph will be displayed here -->
                <?php generateImageHolder("ka_infocus","ka-childa.svg","ka-childa.html","ka_infectedchilderen_scatterplot.R",2,[25],400,450)?>
            </div>
            </div>
        </div>
        
    </div>

    <div class="container mt-5">
      <div class="row">
        <!-- Column for sections -->
        
      <div class="col-md-12 icu-timeline">
        <h3>Trace History of Clusters</h3>
        <p>We first divided up the cases into clusters from their place of origin, for example "From Europe" or "Pharmaceutical Company in Nanjangud, Mysore". Then in each cluster we begin with patients who got it independently from the place of origin and then recursively plot the patients whom they passed it onto. The resulting graph is tree like and a snap shot is given below. In the interactive graph one can view each cluster separately and zoom in to see the precise trace history for each patient in Karnataka. One can also observe how large each cluster is and how the virus spreads locally from an infected patient. The ages, residence, and place of treatment of the patients have been mentioned as well. Below are the data for different Clusters:
          <ui>
            <li><a href="./Tracehistory/restkar.html">Imported and Local</a></li>
            <li><a href="./Tracehistory/ili.html">Influenza like illness</a></li>
            <li><a href="./Tracehistory/sari.html">Sever Acute Respiratory Infection</a></li>
            <li><a href="./Tracehistory/un.html">Others</a></li>
          </ui>
        </p>
      </div>
      </div>
  </div>
  
  <div class="container mt-5">
      <div class="row">
        <!-- Column for sections -->
        
      <div class="col-md-12 icu-timeline">
        <h3>Trace History of Clusters From Maharashtra</h3>
        <p>Below are the data for different dates in the Cluster of Maharashtra:
          <ui>
            <li><a href="./Tracehistory/mh1kar.html" target="_blank">May 15</a></li>
            <li><a href="./Tracehistory/mh2kar.html" target="_blank">May 15-31</a></li>
            <li><a href="./Tracehistory/mh5kar.html" target="_blank">June 1-5</a></li>
            <li><a href="./Tracehistory/mh6kar.html" target="_blank">June 5-12</a></li>
            <li><a href="./Tracehistory/mh7kar.html" target="_blank">June 12-Cont.</a></li>
          </ui>
        </p>
      </div>
      </div>
  </div>

  
    
    

    
    
  </div>
  <?php include 'footer.html'; ?>
  <!-- Bootstrap JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
